server:
  port: 10666

spring:
  application:
    name: aip-core
  ai:
    dashscope:
      api-key: sk-1e62ec4aa62943709062e161230e191c

    memory:
      redis:
        host: 39.105.37.222
        port: 16379
        password: 111333
        timeout:  5000

aip:
  mcp:
    server:
      api-prefix: /mcp/server
    client:
      base-url: http://127.0.0.1:10667
